disabled_rules:
  - force_cast
  - line_length
  - variable_name_min_length
  - trailing_whitespace
  - nesting
  - opening_brace
excluded:
  - Sources/Container.Arguments.swift
  - Sources/SynchronizedResolver.Arguments.swift
  - Sources/Resolvable.swift
  - Tests
  - Sample-iOS.playground
  - Carthage
