disabled_rules:
  - force_cast
  - line_length
  - nesting
  - opening_brace
  - valid_docs
  - type_name
excluded:
  - Sources/Container.Arguments.swift
  - Sources/SynchronizedResolver.Arguments.swift
  - Sources/Resolver.swift
  - Sample-iOS.playground
  - Carthage
  - Packages
variable_name:
  min_length:
    warning: 1
    error: 1
