disabled_rules:
  - force_cast
  - line_length
  - nesting
  - valid_docs
  - type_name
excluded:
  - Sources/GeneratedCode
  - Sample-iOS.playground
  - Carthage
  - Packages
variable_name:
  min_length:
    warning: 1
    error: 1
