name: Swinject
options:
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
targets:
  Swinject:
    type: framework
    platform: [macOS, iOS, tvOS, watchOS]
    settings:
      MACOSX_DEPLOYMENT_TARGET: '10.10'
      TVOS_DEPLOYMENT_TARGET: '9.0'
      IPHONEOS_DEPLOYMENT_TARGET: '8.0'
      WATCHOS_DEPLOYMENT_TARGET: '2.0'
    scheme:
      testTargets:
        - SwinjectTests_${platform}
    sources:
      - path: Sources
        excludes: ["**/*.erb"]
    preBuildScripts:
      - script: >
          if which sourcery >/dev/null; then
            sourcery
          else
            echo "warning: Sourcery not installed, download from https://github.com/krzysztofzablocki/Sourcery"
          fi
        name: Sourcery
    postCompileScripts:
      - script: >
          if which swiftformat >/dev/null; then
            swiftformat .
          else
            echo "warning: SwiftLint not installed, download from https://github.com/nicklockwood/SwiftFormat"
          fi
        name: SwiftFormat
      - script: >
          if which swiftlint >/dev/null; then
            swiftlint autocorrect
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        name: SwiftLint
  SwinjectTests:
    type: bundle.unit-test
    platform: [macOS, iOS, tvOS, watchOS]
    settings:
      MACOSX_DEPLOYMENT_TARGET: '10.10'
      TVOS_DEPLOYMENT_TARGET: '9.0'
      IPHONEOS_DEPLOYMENT_TARGET: '8.0'
      WATCHOS_DEPLOYMENT_TARGET: '2.0'
    scheme: {}
    sources:
      - path: Tests
        excludes: [LinuxMain.swift]
    dependencies:
      - target: Swinject_${platform}
      - carthage: Quick
      - carthage: Nimble
