name: TestingV2
on:
  workflow_dispatch:
    inputs:
        name:
          description: 'Random Parameter'
          required: false
          default: ''
  pull_request:
    branches:
    - github-actions
jobs:
  test:
    name: Testing iOS Framework
    runs-on: macOS-latest
    strategy:
      matrix:
       include:
         - platform-version: iOS
           JOB: "XCODE"
           DEST: "OS=14.0,name=iPhone 8"
           SCHEME: "Swinject-iOS"
           SDK: "iphonesimulator"
           ACTION: "test"
           PLATFORM: "iOS"
         - platform-version: macOS
           JOB: "XCODE"
           DEST: "arch=x86_64"
           SCHEME: "Swinject-macOS"
           SDK: "macosx"
           ACTION: "test"
           PLATFORM: "OSX"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Testing iOS app
        run: exec ./.github/scripts/test_script.sh