name: Testing
# on:
#   pull_request:
#     branches:
#     - master
jobs:
  test:
    name: Testing iOS Framework
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      # - name: Force XCode 12.5.1
      #   run: sudo xcode-select -switch /Applications/Xcode_12.5.1.app
      # - name: Testing Swift package
      #   run: exec ./.github/scripts/test_swift_package.sh
      - name: Testing iOS app
        run: exec ./.github/scripts/test_script.sh